# Generated by Django 4.2.15 on 2024-10-06 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date', 'booking_time']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_message',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'booking_date', 'booking_time')},
        ),
    ]
